export const category = [
    {"Sl. No.":1,"Name":"Yashwantrao Dattatraya Yadav","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":2,"Name":"Sanjay Kapadekar","Gender (M/F)":"M","Location":"Mahavir Nagar, Pandharpur","Occupation":"FMCG Distributor","Category":"Some other Sector"},
{"Sl. No.":3,"Name":"Arvind Dorwat","Gender (M/F)":"M","Location":"Station ROad, Pandharpur","Occupation":"LEDP Training","Category":"Culture, Arts & Tourism"},
{"Sl. No.":4,"Name":"Kunal R. Kawathekar","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Retail","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":5,"Name":"Akshay Ashok Wadadekar","Gender (M/F)":"M","Location":"Isbavi, Pandharpur","Occupation":"Poultry Farm","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":6,"Name":"Jitendra Jayprakash Karade","Gender (M/F)":"M","Location":"Chaitanya Nagar Pandharpur","Occupation":"Farming, Grape farming","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":7,"Name":"Shubham Sunil Yadav","Gender (M/F)":"M","Location":"Navipeth, Pandharpur","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":8,"Name":"Deepak Vasudev Wadadekar","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Cattle feed distributor   & goat farmer & poultry farmer","Category":"Culture, Arts & Tourism"},
{"Sl. No.":9,"Name":"Prasad Maruti Satpute","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"UPVC Building Material Manufacturing","Category":"Culture, Arts & Tourism"},
{"Sl. No.":10,"Name":"Sandeep Bharat Patil","Gender (M/F)":"M","Location":"Wakhari, Pandharpur","Occupation":"Sarki Pend Manufacturing Unit","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":11,"Name":"Gurudev Suresh Kurnawal","Gender (M/F)":"M","Location":"Wakhari, Pandharpur","Occupation":"CA","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":12,"Name":"Akshay pavankumar shah","Gender (M/F)":"M","Location":"Navipeth, Pandharpur","Occupation":"CA in practice","Category":"Some other Sector"},
{"Sl. No.":13,"Name":"Rushikesh M. Bhattad","Gender (M/F)":"M","Location":"Gandhi road, nath chouk, Pandharpur","Occupation":"Cloth merchant","Category":"Housing, Infra & Transport"},
{"Sl. No.":14,"Name":"Rahul Bhattad","Gender (M/F)":"M","Location":"Mahadwar Pandharpur","Occupation":"Cloth merchant","Category":"Housing, Infra & Transport"},
{"Sl. No.":15,"Name":"Dr.Sagar Bhosale","Gender (M/F)":"M","Location":"Mahadwar Pandharpur","Occupation":"Arth packaging","Category":"Housing, Infra & Transport"},
{"Sl. No.":16,"Name":"Mahesh Shashikant Khiste","Gender (M/F)":"M","Location":"Bhosale chouk, Pandharpur","Occupation":"journalist,hostel","Category":"Housing, Infra & Transport"},
{"Sl. No.":17,"Name":"Dr.D.S.Choudhari","Gender (M/F)":"M","Location":"Patkul,Taluka- Mohol,","Occupation":"Professor","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":18,"Name":"Shripad Damodar Bhivrao","Gender (M/F)":"M","Location":"Wangikarnagar, Pandharpur","Occupation":"Food processing unit, cafe,engineering firm","Category":"Housing, Infra & Transport"},
{"Sl. No.":19,"Name":"Vitthal Madhukar Jadhav","Gender (M/F)":"M","Location":"Bouhali, Taluka- Pandharpur","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":20,"Name":"Mane Prajit Ashok","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":21,"Name":"Shashank Bharat Thite","Gender (M/F)":"M","Location":"Mauli Nagar, Pandharpur","Occupation":"-","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":22,"Name":"Aditya Idate","Gender (M/F)":"M","Location":"Bhaktimarg, Pandharpur","Occupation":"Tea production,Unisex salon","Category":"Housing, Infra & Transport"},
{"Sl. No.":23,"Name":"Ravindra Bhosale","Gender (M/F)":"M","Location":"Bhosale chouk, Pandharpur","Occupation":"-","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":24,"Name":"Mithun G. Maniyar","Gender (M/F)":"M","Location":"SVERI COP,nPandharpur","Occupation":"Farmer","Category":"Culture, Arts & Tourism"},
{"Sl. No.":25,"Name":"Sanjay Pralhad Maske","Gender (M/F)":"M","Location":"Market yard, Pandharpur","Occupation":"Software engineer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":26,"Name":"Ganesh Balkrushna Atkale","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Professor","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":27,"Name":"Satish Vasant Mandave","Gender (M/F)":"M","Location":"Takali road, pandharpur","Occupation":"Coffee shop & ice cream distributor","Category":"Housing, Infra & Transport"},
{"Sl. No.":28,"Name":"Vishal B Salunkhe","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Pruthvi Hotel","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":29,"Name":"Kiran Shankar Ghadage","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Two wheeler garage","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":31,"Name":"Sagar Gopal Badave","Gender (M/F)":"M","Location":"Bhaktimarg, Pandharpur","Occupation":"Export import business","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":32,"Name":"Koustubh Satish Hendre","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Farmer/businessman","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":33,"Name":"Kulkarni Suhas Haribhau","Gender (M/F)":"M","Location":"Shivaji chouk, Pandharpur","Occupation":"Stationery shop owner","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":34,"Name":"Dipak dilip thite","Gender (M/F)":"M","Location":"Gajanan Nagar, Pandharpur","Occupation":"Business","Category":"Housing, Infra & Transport"},
{"Sl. No.":35,"Name":"Pandurang Ghanti","Gender (M/F)":"M","Location":"Ghongadi galli, Pandharpur","Occupation":"Trading & agency","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":36,"Name":"Vitthal Prakash Katkamwar","Gender (M/F)":"M","Location":"Navi peth, Pandharpur","Occupation":"Family Cloth showroom","Category":"Some other Sector"},
{"Sl. No.":37,"Name":"Rajesh Kapadikar (Panchali Showroom)","Gender (M/F)":"M","Location":"Mahaveer Nagar, Pandharpur","Occupation":"Advocate","Category":"Some other Sector"},
{"Sl. No.":38,"Name":"Adv.Bhagwan vasantrao Bhadule","Gender (M/F)":"M","Location":"Shadule road, Pandharpur","Occupation":"Enemployed","Category":"Culture, Arts & Tourism"},
{"Sl. No.":39,"Name":"Dilip Gnyaneshwar Gurav","Gender (M/F)":"M","Location":"Gopalpur","Occupation":"Farmer","Category":"Culture, Arts & Tourism"},
{"Sl. No.":40,"Name":"Sachin Kulkarni","Gender (M/F)":"M","Location":"Gajanan Nagar","Occupation":"Bricks plant & farming","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":41,"Name":"Shreyas Sachin Kulkarni","Gender (M/F)":"M","Location":"Gajanan Nagar","Occupation":"Student","Category":"Housing, Infra & Transport"},
{"Sl. No.":42,"Name":"Shardul S. Nalbilwar","Gender (M/F)":"M","Location":"Isbvi","Occupation":"Construction as builder","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":43,"Name":"Lohakare Balaji Dattatray","Gender (M/F)":"M","Location":"Begampur","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":44,"Name":"Lakhan Bharat Mane","Gender (M/F)":"M","Location":"Begampur","Occupation":"All type of chain link manufacturing","Category":"Some other Sector"},
{"Sl. No.":45,"Name":"Tukaram B. Yadav","Gender (M/F)":"M","Location":"Mangalweda","Occupation":"ICICI Bank, Job","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":46,"Name":"Akash Sunil Mehtre","Gender (M/F)":"M","Location":"Begumpur","Occupation":"Agency","Category":"Some other Sector"},
{"Sl. No.":47,"Name":"Javid L Shaikh","Gender (M/F)":"M","Location":"Begumpur","Occupation":"Member of Panchayat, Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":48,"Name":"Akash Sushil Ingale","Gender (M/F)":"M","Location":"Mangalweda","Occupation":"Business/Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":49,"Name":"Toraskar Soham Dhashrath","Gender (M/F)":"M","Location":"Sarkoli","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":50,"Name":"Shweta Arjun Bahire","Gender (M/F)":"F","Location":"Umbergaon","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":51,"Name":"Siddhika Althap Inamdar","Gender (M/F)":"M","Location":"Kasegoan","Occupation":"Farming","Category":"Some other Sector"},
{"Sl. No.":52,"Name":"Jaisree Vijay Madane","Gender (M/F)":"F","Location":"Bhalabali","Occupation":"Job and farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":53,"Name":"Mahesh Hanumanta Kagate","Gender (M/F)":"M","Location":"Malshiras","Occupation":"Government Contractor","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":54,"Name":"Anil Sopan Repad","Gender (M/F)":"M","Location":"Tulsi, Madha Taluka","Occupation":"Business Farming","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":55,"Name":"Ram Raje M. Deshmukh","Gender (M/F)":"M","Location":"Kasegaon","Occupation":"Farming","Category":"Some other Sector"},
{"Sl. No.":56,"Name":"Ramchandra Baliram Bhingare","Gender (M/F)":"M","Location":"Malshiras","Occupation":"Milk Production, Earthmovers","Category":"Some other Sector"},
{"Sl. No.":57,"Name":"Santosh Chandrashekar Halkude","Gender (M/F)":"M","Location":"Madha","Occupation":"Job","Category":"Housing, Infra & Transport"},
{"Sl. No.":58,"Name":"Ankush Manohar Bedage","Gender (M/F)":"M","Location":"Gurasade","Occupation":"Farming or nursery","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":59,"Name":"Naneshwar/ Mauli A. Atkale","Gender (M/F)":"M","Location":"Shegaon","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":60,"Name":"Rohan Anurath Vansade","Gender (M/F)":"M","Location":"Gopalpur","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":61,"Name":"Machindra Pandurang Gade","Gender (M/F)":"M","Location":"Mohol","Occupation":"Electrical Contractor/Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":62,"Name":"Abhijeet Subhash Bhosle","Gender (M/F)":"M","Location":"Gopalpur","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":63,"Name":"Saurabh Machindra Gade","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Student","Category":"Some other Sector"},
{"Sl. No.":64,"Name":"Rohit Anurath Vansale","Gender (M/F)":"M","Location":"Gopalpur","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":65,"Name":"Ramzan saheblal shaikh","Gender (M/F)":"M","Location":"Malshiras (home near Akluj), Kasegaon (lives)","Occupation":"Farmer","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":66,"Name":"No name","Gender (M/F)":"M","Location":"Nevare","Occupation":"Farmer","Category":"Some other Sector"},
{"Sl. No.":67,"Name":"Prajwal Kale","Gender (M/F)":"M","Location":"Bhosle Chowk, Pandharpur","Occupation":"Clothing, retail shop","Category":"Culture, Arts & Tourism"},
{"Sl. No.":68,"Name":"Nikhil Subhash Shaha","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Manufacturing of food product","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":69,"Name":"Dhananjay Choudhari","Gender (M/F)":"M","Location":"Patkul Taluka","Occupation":"Service","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":70,"Name":"Milind Kulkarni","Gender (M/F)":"M","Location":"SVERI","Occupation":"Service","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":71,"Name":"Netaji Patil","Gender (M/F)":"M","Location":"Dhayati, Sangola","Occupation":"Farmer","Category":"Some other Sector"},
{"Sl. No.":72,"Name":"Aniket Sunil Langote","Gender (M/F)":"M","Location":"Junakaradnaka","Occupation":"Farmer","Category":"Some other Sector"},
{"Sl. No.":73,"Name":"Shankar Godse","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Contractor Business","Category":"Housing, Infra & Transport"},
{"Sl. No.":74,"Name":"Hazare Prathamesh Ramesh","Gender (M/F)":"M","Location":"Hajare Galli, Mangalweda","Occupation":"Enemployed","Category":"Culture, Arts & Tourism"},
{"Sl. No.":75,"Name":"Vaibhav More","Gender (M/F)":"M","Location":"Ghunge Galli, Mangalweda","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":76,"Name":"Vaibhav Audumbar Doiphode","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Civil Engineer & MBA","Category":"Some other Sector"},
{"Sl. No.":77,"Name":"Kumar Ramchandra Inamdar","Gender (M/F)":"M","Location":"Gardi, Pandharpur","Occupation":"Farmer & Professor","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":78,"Name":"Swananda Hanumanta Pawar","Gender (M/F)":"M","Location":"Akluj, Malshiras Taluka","Occupation":"Computer operator","Category":"Some other Sector"},
{"Sl. No.":79,"Name":"Padmakar Bhajandas Bhosle","Gender (M/F)":"M","Location":"Papri, Mohol Taluka","Occupation":"Milk production and farmer","Category":"Housing, Infra & Transport"},
{"Sl. No.":80,"Name":"Sanjay Babaso Deshmukh","Gender (M/F)":"M","Location":"Kasegaon","Occupation":"Farmer","Category":"Culture, Arts & Tourism"},
{"Sl. No.":81,"Name":"Vijay Vithal Deshmukh","Gender (M/F)":"M","Location":"Kasegaon, Pandharpur Taluka","Occupation":"Farmer","Category":"Some other Sector"},
{"Sl. No.":82,"Name":"Revathy Khandukadam","Gender (M/F)":"F","Location":"Vedapur, Akluj","Occupation":"Service","Category":"Some other Sector"},
{"Sl. No.":83,"Name":"Narale Minakshi Tukaram","Gender (M/F)":"F","Location":"Paryanti, Man Taluka, Satara District","Occupation":"Student","Category":"Some other Sector"},
{"Sl. No.":84,"Name":"Swaraj Madhav Chavan","Gender (M/F)":"M","Location":"Suste, Pandharpur","Occupation":"Construction","Category":"Some other Sector"},
{"Sl. No.":85,"Name":"Kedar Digambar Sudke","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Civil Construction","Category":"Some other Sector"},
{"Sl. No.":86,"Name":"Akash Rajendra Mete","Gender (M/F)":"M","Location":"-","Occupation":"-","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":87,"Name":"Kiran Gorakh Gaikwad","Gender (M/F)":"M","Location":"Ambe, Pandharpur","Occupation":"Job","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":88,"Name":"Atkale Nilesh Rajkumar","Gender (M/F)":"M","Location":"Bhakti Marg, Pandharpur","Occupation":"Civil Contractor","Category":"Some other Sector"},
{"Sl. No.":89,"Name":"Rohit Rajendra Surwase","Gender (M/F)":"M","Location":"Bhandishegaon","Occupation":"Pharmacist","Category":"Health & Well-being"},
{"Sl. No.":90,"Name":"Rahul Koli","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Pharmacist","Category":"Housing, Infra & Transport"},
{"Sl. No.":91,"Name":"Samir Paigambar Shaikh","Gender (M/F)":"M","Location":"Mundhewadi, Pandharpur","Occupation":"Organic fertilizers","Category":"Health & Well-being"},
{"Sl. No.":92,"Name":"Somnath Sadashiv Devkar","Gender (M/F)":"M","Location":"Bhamburdi, Solapur","Occupation":"Medical Representative","Category":"Health & Well-being"},
{"Sl. No.":93,"Name":"Yogesh Arun Borade","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Layer Poultry Farm","Category":"Some other Sector"},
{"Sl. No.":94,"Name":"Vishal Sudhakar Shalu","Gender (M/F)":"M","Location":"Isbhavi, Pandharpur","Occupation":"Job","Category":"Quality Education & Skilling"},
{"Sl. No.":95,"Name":"Pooja Babruvahan Ronge","Gender (M/F)":"F","Location":"Golden Colony, Pandharpur","Occupation":"Petrol pump & milk by- products production plant","Category":"Some other Sector"},
{"Sl. No.":96,"Name":"Dhaireya Laxmi","Gender (M/F)":"F","Location":"SVERI campus, Pandharpur","Occupation":"Tuition Teacher","Category":"Some other Sector"},
{"Sl. No.":97,"Name":"Ankita Suraj Ashtekar","Gender (M/F)":"F","Location":"Gajanan Nagar, Pandharpur","Occupation":"Sanvi's Cakes, Arts & Crafts Classes","Category":"Quality Education & Skilling"},
{"Sl. No.":98,"Name":"Smita Dubal","Gender (M/F)":"F","Location":"Link Road, Pandharpur","Occupation":"IT services (Salesforce)","Category":"Health & Well-being"},
{"Sl. No.":99,"Name":"Dr. Sneha Suraj Ronge","Gender (M/F)":"F","Location":"Golden Colony, Pandharpur","Occupation":"Doctor(OBGYN)","Category":"Health & Well-being"},
{"Sl. No.":100,"Name":"Meera Ramakant Rede- Patil","Gender (M/F)":"F","Location":"Bhakti Marg, Pandharpur","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":101,"Name":"Sarita Mahesh Mane","Gender (M/F)":"F","Location":"Namdev Mandir, Pandharpur","Occupation":"Prasad items seller","Category":"Some other Sector"},
{"Sl. No.":102,"Name":"Mayura Milind Laad","Gender (M/F)":"F","Location":"Namdev Temple, Pandharpur","Occupation":"Enemployed","Category":"Sustainable Food & Agriculture"},
{"Sl. No.":103,"Name":"Sujata Pangaonkar","Gender (M/F)":"F","Location":"Sahkarchowk, Pandharpur","Occupation":"Enemployed","Category":"Some other Sector"},
{"Sl. No.":104,"Name":"Swati Pawar","Gender (M/F)":"M","Location":"Pandharpur","Occupation":"Enemployed","Category":"Some other Sector"}

]